name: non_stop
description: "A None Stop."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  cached_network_image: ^3.4.1
  connectivity_plus: ^7.0.0
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  dots_indicator: ^4.0.1
  easy_localization: ^3.0.8
  file_picker: ^10.3.3
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_easyloading: ^3.0.5
  flutter_local_notifications: ^19.5.0
  flutter_phoenix: ^1.1.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.2
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0
  google_fonts: ^6.3.2
  iconsax: ^0.0.8
  image_picker: ^1.2.0
  jiffy: ^6.4.3
  json_annotation: ^4.9.0
  loading_indicator: ^3.1.1
  lottie: ^3.3.1
  page_transition: ^2.2.1
  pinput: ^5.0.1
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.9.0
  retrofit_generator: ^10.1.3
  share_plus: ^12.0.0
  shared_preferences: ^2.5.3
  skeletonizer: 1.4.2
  table_calendar: ^3.2.0
  top_snackbar_flutter: ^3.3.0
  url_launcher: ^6.3.2

dev_dependencies:
  build_runner: ^2.4.14

  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.3

flutter:
  uses-material-design: true

  # assets:
  assets:
    - assets/svgs/
    - assets/pngs/
    - assets/languages/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Swissra
      fonts:
        - asset: assets/fonts/alfont_com_AlFont_com_Swissra-Normal-1.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
