name: non_stop
description: "A None Stop."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  pinput: ^5.0.1

  cached_network_image: ^3.4.1

  cupertino_icons: ^1.0.8

  dots_indicator: ^4.0.1

  table_calendar: ^3.2.0

  # ğŸ”¹ Flutter screen util for responsive design
  flutter_screenutil: ^5.9.3

  # ğŸ”¹ Google Fonts
  google_fonts: ^6.3.2

  # ğŸ”¹ Flutter Svg
  flutter_svg: ^2.2.2

  # ğŸ”¹ Firebase Core
  firebase_core: ^4.2.0
  # ğŸ”¹ Firebase Cloud Messaging
  firebase_messaging: ^16.0.3

  # ğŸ”¹ Top Snackbar Flutter for beautiful top snack bars
  top_snackbar_flutter: ^3.3.0

  # ğŸ”¹ Flutter Local Notifications
  flutter_local_notifications: ^19.5.0

  # ğŸ”¹ Get It Dependency Injection
  get_it: ^8.2.0

  # ğŸ”¹ Dio HTTP Client
  dio: ^5.9.0

  # ğŸ”¹ Retrofit
  retrofit: ^4.9.0
  retrofit_generator: ^10.1.3

  # ğŸ”¹ Pretty Dio Logger
  pretty_dio_logger: ^1.4.0

  # ğŸ”¹ Shared Preferences
  shared_preferences: ^2.5.3

  # ğŸ”¹ Flutter Secure Storage
  flutter_secure_storage: ^9.2.4

  # ğŸ”¹ Share Plus
  share_plus: ^12.0.0

  # ğŸ”¹ Url Launcher
  url_launcher: ^6.3.2

  # ğŸ”¹ Jiffy Date Formatter
  jiffy: ^6.4.3

  # ğŸ”¹ Flutter Bloc (Cubit)
  flutter_bloc: ^9.1.1

  # ğŸ”¹ Flutter Page Transition
  page_transition: ^2.2.1

  # ğŸ”¹ Freezed
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0

  # ğŸ”¹ Iconsax
  iconsax: ^0.0.8

  # ğŸ”¹ Json Annotation
  json_annotation: ^4.9.0

  # ğŸ”¹ Loading Indicator
  loading_indicator: ^3.1.1

  # ğŸ”¹ Lottie
  lottie: ^3.3.1

  # ğŸ”¹ Skeletonizer
  skeletonizer: 1.4.2

  # ğŸ”¹ Flutter Dotenv
  flutter_dotenv: ^6.0.0

  # ğŸ”¹ Connectivity Plus for network info
  connectivity_plus: ^7.0.0

  # ğŸ”¹ Easy Localization for multi-language support
  easy_localization: ^3.0.8

  # ğŸ”¹ Flutter EasyLoading for loading indicators
  flutter_easyloading: ^3.0.5

  # ğŸ”¹ Flutter Phoenix for hot reload
  flutter_phoenix: ^1.1.1

dev_dependencies:
  build_runner: ^2.4.14
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.9.3

flutter:


  uses-material-design: true


  # assets:
  assets:
    - assets/svgs/
    - assets/pngs/
    - assets/languages/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Swissra
      fonts:
        - asset: assets/fonts/alfont_com_AlFont_com_Swissra-Normal-1.ttf

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

